Dz7 2
ruvaleev/thinknetica pull request #9
Opened 2018-04-21 09:58 UTC by ruvaleev

2018-04-22 09:38 UTC, vkurennov requested changes

2018-04-22 09:38 UTC, vkurennov commented on app/assets/javascripts/answers.js.coffee
> +# Скрываем лучший ответ из общего списка ответов
А зачем его скрывать при загрузке страницы? Лучше сделать скоуп в моделях и выбирать все не лучшие ответы и показыавть их в списке и также сделать метод в модели вопроса, возвращающий лучший ответ и вывести его отдельно.

2018-04-22 09:38 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :load_answer, except: [ :create ]
У массивов не ставятся пробелы после `[` и перед `]`

2018-04-22 09:38 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def award
Слишком много логики в контроллере. Контроллер не должен содержать бизнес-логик (логику, меняющую состояние системы). Он должен вызывать нужные методы модели и выполнять нужный рендеринг. Так что всю логику нужно перенсти в метод модели, а здесь просто вызывать его.

2018-04-22 09:38 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @former_best_answer = @question.answers.find_by(award: 1) #находим прежний лучший ответ, чтобы показать его во вьюхе, если понадобится
Используй не 1 и 0 для логических значений, а true и false. Само собой, что и в таблице для этого нужно тип поля указать как boolean

2018-04-22 09:38 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.update(award: 1) #делаем выбранный ответ лучшим
У тебя несколько апдейтов разных объектов, нужно их все заключить в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными.

2018-04-22 09:38 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  div id="best"
В slim можно такие вещи сокращать, писать просто `#best `, то же для дивов с классом, можно писать просто `.some_class`

2018-04-22 09:38 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    - unless @question.answers.find_by(award: 1).nil?
Запросы в видах - очень плохая практика, сделай методы в модели, которые бы возвращали нужные данны и здесь их используй.

2018-04-22 09:38 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      = render @question.answers.find_by(award: 1), best: true
Зачем тут передается параметр best?

2018-04-22 09:38 UTC, vkurennov commented on app/views/questions/update.js.erb
> +$('#tr<%= @question.id %>').after('<%= j render @question, q: @question %>');
Не используй параметр q, для анонимных паршалов, когда передаешь объект, в самом парашле он доступен как локальная переменная question (т.е. также, как сам паршл называется)

2018-04-22 09:38 UTC, vkurennov commented on config/routes.rb
> +    patch 'award', on: :member
Отступ, это же вложенное выражение.

2018-04-22 09:38 UTC, vkurennov commented on db/migrate/20180413133124_add_award_ref_to_answers.rb
> +    add_column :answers, :award, :integer
Измени  тип на boolean, и сразу добавь значение false как значение по-умолчанию

2018-04-23 16:25 UTC, vkurennov requested changes

2018-04-23 16:25 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.make_best
Ты забыл про условия: выбрать ответ лучшим может только автор вопроса

2018-04-23 16:25 UTC, vkurennov commented on app/models/answer.rb
> +    Question.find(self.question_id).answers.update(award: false)
1. У тебя есть ассоциация с вопросом, достаточно написать question и ты как раз получишь связанный вопрос, через find искать не нужно.
2. Используй update_all для обновления всех ответов

2018-04-23 16:25 UTC, vkurennov commented on app/models/answer.rb
> +    self.update(award: true)
1. Не стоит использовать self  без необходимости, здесь он лишний
2. Т.к. у тебя несколько апдейтов, нужно применить [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными.

2018-04-23 16:25 UTC, vkurennov commented on app/models/question.rb
> +  def not_awarded_answers
Попробуй сделать это при помощи запроса where, все выборки нужно делать именно языком запросов, чтобы работала база, это горзадо быстрее и эффективнее

2018-04-23 16:25 UTC, vkurennov commented on app/models/answer.rb
> +  scope :best, ->(question) { where(award: true, question_id: question.id) }
Не нужно делать скоуп с параметром вопроса, скоупы "склеиваются", поэтому достаточно будет вызывать так: `question.answers.best`, в этом случае фильтр по вопросу будет применен автоматом, потому что скоуп применяется не ко всем ответам, а только к ответам конкретного вопроса. Соответственно, в скоупе questio_id будет не нужен, как и параметр

2018-04-23 16:25 UTC, vkurennov commented on app/models/answer.rb
> +  def make_best
А где тесты модели на этот метод?

2018-04-24 17:18 UTC, ruvaleev commented on app/models/question.rb
> +  def not_awarded_answers
Я пробовал и запросом where, и скоупом - в результате и то, и другое не работает в тестах (не рендерятся, хотя реальный пользователь их видит, все ок)

2018-04-25 08:22 UTC, vkurennov requested changes

2018-04-25 08:22 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.make_best if current_user.author_of?(@answer)
Выбрать лучший ответ может автор **вопроса**. Вопроса, а не ответа.

2018-04-25 08:22 UTC, vkurennov commented on app/models/answer.rb
> +      update(award: true)
Транзакция откатывается только в случае исключения, поэтому здесь надо применить `update!`, этот метод в отличие от обычной версии выбросит исключение, если не сможет сохранить объект

2018-04-25 08:22 UTC, vkurennov commented on app/models/question.rb
> +  def not_awarded_answers
Ты же потом будешь этот код показывать работодателю, и это будет смотреться крайне непрофессионально. Поэтому надо разобраться, почему в тестах не работает.
Но, кажется, я понял, в чем дело, см. комментарий к acceptance-тестам по выбору лучшего ответа.

2018-04-25 08:22 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = render @question.not_awarded_answers
Попробуй здесь сделать так: `@question.not_awarded_answers.all`, посмотри, поможет ли это пройти тестам.

2018-04-25 08:22 UTC, vkurennov commented on app/views/answers/_answer.html.slim
>  table class="last_answer"
можно писать так: `table.last_answer`

2018-04-25 08:22 UTC, vkurennov commented on spec/acceptance/edit_answer_spec.rb
> +        answer
Если объект нужен ДО теста, то объяви его через `let!`

2018-04-25 08:22 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  it 'makes best' do
Этого не достаточно, нужен еще тест, когда есть уже другой лучший ответ и надо проверить, что он перестает быть лучшим

2018-04-25 08:22 UTC, vkurennov commented on spec/acceptance/choose_best_answer_spec.rb
> +    scenario 'for own question', js: true do
Кажется, я понял, почему у тебя тест на проходит. У тебя же не создаются другие ответы. У тебя создается только лучший ответ. Тебе нужно создать к этому же вопросу несколько ответов, один из них выбрать лучшим, тогда у тебя будут и в тестах другие, не лучшие, ответы появляться

2018-04-25 08:22 UTC, vkurennov commented on app/models/question.rb
> +  def not_awarded_answers
Кстати, раз у тебя есть публичный метод, то его надо протестировать в тестах модели Question

2018-04-26 09:33 UTC, vkurennov requested changes

2018-04-26 09:33 UTC, vkurennov commented on spec/acceptance/choose_best_answer_spec.rb
> +      best_answer
Еще раз: если данные нужны сразу при начале теста, объявляй их через `given!`

2018-04-26 09:33 UTC, vkurennov commented on spec/acceptance/choose_best_answer_spec.rb
> +        expect(page).to have_content(best_answer.body)
Так, но ведь тут этот тест никак не привязывается к другим ответам, т.е. он должен проходить в любом случае. Он проходит или нет?

2018-04-26 09:33 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    expect( former_best_answer.award ).to eq(0)
Лучше вообще писать так: `exepect(former_best_answer).to_not be_award`

А по поводу 0 и 1: у тебя просто тестовая база не подхватила изменения атрибута на boolean, когда откатываешь и меняешь миграцию, она автоматически не применяется к тестовой базе. Чтобы привести схемы данных для дев и тестов в общее состоятние, выполни команду `rails db:test:prepare`

2018-04-26 09:33 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    former_best_answer.make_best
Нельзя задавать начальные значения через вызов тестируемого метода, потому что в этом методе может быть баг и из-за этого тест будет ложно-положительным. Нужно в явном виде установить флаг award в true при создании этого ответа.
И используй уже `let!` для задания данных, которые нужны для теста

2018-04-26 18:11 UTC, merged